services:
  - type: web
    name: anything-llm-docker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_FRONTEND_API
        sync: false
